version: '3'
services:
  api:
    container_name: habit_test_api
    ports:
      - 3000:3000
    environment: 
      - PGUSER=guymargalith
      - PGHOST=db
      - PGPASSWORD=password
      - PGDATABASE=habit_tracker_test
      - PGPORT=5432
      - NODE_ENV=test
    depends_on: 
      - db
    tty: true
    command: bash -c "npm install && npm run seedDev && npm run dev"
  db:
    container_name: habit_test_db
    expose:
      - "5432"
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=abit_tracker_test
      - POSTGRES_USER=guymargalith
      - POSTGRES_PASSWORD=password
volumes:
  test_db:
